name: Pulumi
on:
  workflow_dispatch:
    inputs:
      allocated_storage:
        required: true
        type: number
      database_name:
        required: true
        type: string
      db_username:
        required: true
        type: string
      db_password:
        required: true
        type: string
      port_context:
        required: false
        type: string 

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install dependencies
          run: npm install
      - name: Authenticate to Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
      - name: Install and Inject ESC Environement Variables
        uses: pulumi/esc-action@v1
        with:
          environment: 'demo/cloud-access/aws-oidc'
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: demo/Temporal-IaC/dev
          work-dir: ./
        args: --yes --non-interactive